### ISSUE TITLE
curious about `passRetained` in event tap callback

### ISSUE THREAD

**Issue by godbout** [creasty/Keyboard#25]
https://github.com/creasty/Keyboard/blob/6ac166679e9798128f1a7a7883ff189154b42539/keyboard/Core/EventManager.swift#L27

quite noob to macOS development here. been through some coding and loads of documentation in the past few weeks, and i don't get why `passRetained` is used in your event tap callback rather than `passUnretained`. i'm pretty sure you're correct, but i can't reason why. from the doc (https://developer.apple.com/documentation/coregraphics/cgeventtapcallback#) it appears the event is owned by the caller. if you modify it, wouldn't you pass it without retaining it? if you use `passRetained`, then when do you release it?

**Comment by creasty** [comment]
I hate to break it to you but I'm no expert either. This has been the first and only macOS app I've ever created so far.
Perhaps, the simplest reason as to why `passRetained` being used here is that I found an implementation that used passRetained and I didn't give it much thought...

For what it’s worth, I have never had a memory issue — Consumption-wise, it only uses 15MB at a startup and a week later.
So I assume it might not be critical if we use `passRetained` or somehow it releases memory at some point. 🤷‍♂️ 

Anyway, now that you've mentioned it, I've tested both versions and examined the memory usage.
The below are the result of Instruments where I waited 10 sec after the startup, pressed as many random keys as possible for 30 sec, and waited another 20 sec to stop.

### `passUnretained`

<img width="1284" alt="Screen Shot 2020-12-20 at 17 34 46" src="https://user-images.githubusercontent.com/1695538/102709031-21190380-42ea-11eb-83b6-0f820d50be11.png">

### `passRetained`

<img width="1284" alt="Screen Shot 2020-12-20 at 17 36 40" src="https://user-images.githubusercontent.com/1695538/102709044-355d0080-42ea-11eb-84c9-7a6c017c850e.png">

<img width="1284" alt="Screen Shot 2020-12-20 at 17 39 24" src="https://user-images.githubusercontent.com/1695538/102709061-51f93880-42ea-11eb-8092-2b860aac3689.png">

You're right, there were actually memory leaks.
Wonder how it hasn't been a problem for me...

**Comment by godbout** [comment]
ah. thanks for taking the time. and sorry, i meant no macOS/iOS/Swift/Objective-C development here.

i've heard about `Instruments` but haven't open it yet. seems another big chunk of time and exploration needed to understand that one correctly too. but i'm confused—again—now with your screenshots. i would have expected the leaks to appear on the `passRetained` one rather than the `passUnretained`? actually, if `passRetained` doesn't show any leak, i would have expected `passUnretained` to simply crash. so, am i misunderstanding how `Instruments` is reporting leaks?

btw. thanks for making this repo public. inspiring, beautiful code.

**Comment by creasty** [comment]
> but i'm confused—again—now with your screenshots. i would have expected the leaks to appear on the `passRetained` one rather than the `passUnretained`?

Oh, shoot. It was the other way around. Swapped the titles.

> btw. thanks for making this repo public. inspiring, beautiful code.

My pleasure.

**Comment by godbout** [comment]
i can die peacefully in my sleep now \o/ 

thanks again for your time.
