### ISSUE TITLE
Capture Magic Mouse tap gestures

### ISSUE THREAD

**Issue by aff** [creasty/Keyboard#28]
Hi and thanks for open sourcing this awesome tool!  

Question: Is it possible to capture Magic Mouse tap gestures (e.g. to simulate tap-to-click)? I´ve tried adding a "print(action)" on line 39 on EventManager.swift, and it seems only keyboard actions trigger anything to the output terminal. Please advise. 

Thanks again and best regards.

**Comment by creasty** [comment]
Currently, it only intercepts keyboard events:
https://github.com/creasty/Keyboard/blob/75dfa78b2120d20c9b2d17b6c314651e28316017/keyboard/AppDelegate.swift#L73

If you want to handle click events, include `leftMouseDown` & `leftMouseUp` to the mask.
c.f., https://developer.apple.com/documentation/coregraphics/cgeventtype

**Comment by aff** [comment]
Hi and many thanks for the suggestion.  I´ve tried adding your suggested code, and even `let eventMask = NSEvent.EventTypeMask.any.rawValue`, but I can still **not** make it catch mouse events (clicks, taps, anything).  Do keyboard and mouse events work differently?

**Comment by creasty** [comment]
Please read the code more carefully.
It worked on my end.

```diff
index 961a81b..9a94825 100644
--- a/keyboard/AppComponent.swift
+++ b/keyboard/AppComponent.swift
@@ -20,6 +20,8 @@ final class AppComponent {
             if let manager = _eventManager {
                 return manager.handle(proxy: proxy, cgEvent: event)
             }
+        case .leftMouseDown:
+            print("leftMouseDown!")
         default:
             break
         }
diff --git a/keyboard/AppDelegate.swift b/keyboard/AppDelegate.swift
index bc39af6..84303b7 100644
--- a/keyboard/AppDelegate.swift
+++ b/keyboard/AppDelegate.swift
@@ -70,7 +70,7 @@ private extension AppDelegate {
     }

     func setupEventTap() {
-        let eventMask = (1 << CGEventType.keyDown.rawValue) | (1 << CGEventType.keyUp.rawValue)
+        let eventMask = (1 << CGEventType.keyDown.rawValue) | (1 << CGEventType.keyUp.rawValue) | (1 << CGEventType.leftMouseDown.rawValue)

         guard let eventTap = CGEvent.tapCreate(
             tap: .cghidEventTap,
```

**Comment by aff** [comment]
Fantastic, thank you! (I missed the AppComponent.swift part, I am sorry and I apologize)
